# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'SHExtension/UIButton'
  pod 'SHExtension/UIColor'
  pod 'SHExtension/UIView'
  pod 'SHCollectionViewFlowLayout'
  pod 'Masonry'

end

post_install do |installer|
  # 1. 遍历项目中所有target
  installer.pods_project.targets.each do |target|
     # 2. 遍历build_configurations
    target.build_configurations.each do |config|
      # 3. 修改build_settings中的ENABLE_BITCODE
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
  
end
